export interface HAQForm {
    part1: {
      label: 'Gastrointestinal',
      section1: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
      };
      section2: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
      };
      section3: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
      };
      section4: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
      };
    };
    part2: {
      label: 'Liver/GB',
      section1: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
        '11': number;
        '12': number;
        '13': number;
        '14': number;
        '15': number;
      };
    };
    part3: {
      label: 'Endocrine',
      section1: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
        '11': number;
        '12': number;
        '13': number;
        '14': number;
      };
      section2: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
        '11': number;
      };
    };
    part4: {
      label: 'Glucose Regulation',
      section1: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
        '11': number;
        '12': number;
        '13': number;
        '14': number;
        '15': number;
      };
      section2: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
      };
    };
    part5: {
      label: 'Cardiovascular',
      section1: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
      };
      section2: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
        '11': number;
      };
    };
    part6: {
      label: 'Mood',
      section1: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
      };
      section2: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
        '11': number;
        '12': number;
        '13': number;
      };
      section3: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
      };
    };
    part7: {
      label: 'Immune',
      section1: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
        '11': number;
        '12': number;
        '13': number;
        '14': number;
        '15': number;
        '16': number;
        '17': number;
        '18': number;
        '19': number;
        '20': number;
        '21': number;
        '22': number;
        '23': number;
        '24': number;
        '25': number;
        '26': number;
        '27': number;
        '28': number;
        '29': number;
        '30': number;
      };
    };
    part8: {
      label: 'Urological',
      section1: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
        '11': number;
      };
    };
    part9: {
      label: 'Musculoskeletal',
      section1: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
      };
      section2: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
        '11': number;
        '12': number;
      };
      section3: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
        '11': number;
        '12': number;
        '13': number;
        '14': number;
        '15': number;
      };
    };
    part10: {
      label: 'CNS & Brain',
      section1: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
        '11': number;
        '12': number;
        '13': number;
        '14': number;
        '15': number;
      };
      section2: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
      };
    };
    part11: {
      label: 'Male',
      section1: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
      };
    };
    part12: {
      label: 'Female',
      section1: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
        '11': number;
        '12': number;
        '13': number;
        '14': number;
        '15': number;
        '16': number;
        '17': number;
        '18': number;
        '19': number;
        '20': number;
        '21': number;
      };
      section2: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
      };
      section3: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
        '11': number;
      };
      section4: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
        '11': number;
        '12': number;
        '13': number;
        '14': number;
        '15': number;
        '16': number;
        '17': number;
      };
      section5: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
      };
      section6: {
        '0': number;
        '1': number;
        '2': number;
        '3': number;
        '4': number;
        '5': number;
        '6': number;
        '7': number;
        '8': number;
        '9': number;
        '10': number;
        '11': number;
        '12': number;
        '13': number;
        '14': number;
      };
    };
};
